on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install browsers' system dependencies
        run: npx playwright install-deps
      - name: Install tests' dependencies
        run: npm ci
      - name: Run tests
        run: npm test
