on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Run tests
        run: docker-compose up
